### ISSUE TITLE
can't open dataset

### ISSUE THREAD

**Issue by ta-xiang** [LLluoling/PENS-Personalized-News-Headline-Generation#14]
https://msnews.github.io/pens.html

https://msrshare.blob.core.windows.net/msr/training_set.zip
https://msrshare.blob.core.windows.net/msr/test_set.zip

I can't open these two url,please help me! 0v0

**Comment by T-Atlas** [comment]
Please ref.
https://huggingface.co/datasets/THEATLAS/PENS
