### ISSUE TITLE
Training Personalization Generator is wrong

### ISSUE THREAD

**Issue by 1607722534** [LLluoling/PENS-Personalized-News-Headline-Generation#6]
actor_network_loss = (actor_network_loss * masks)/length_torch
RuntimeError: The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1

**Comment by AlfredAM** [comment]
same issue.

actor_network_loss shape:  torch.Size([4])
masks shape:  torch.Size([4, 16])
length_torch shape:  torch.Size([4])
Traceback (most recent call last):
  File "pipeline (pretrain & train & test)-ac2.py", line 101, in <module>
    trainer.train(data_loader, train_option='a2c')
  File "/home/recom/pens/pensmodule/Generator/train.py", line 239, in train
    actor_network_loss = (actor_network_loss * masks) / length_torch
RuntimeError: The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1

**Comment by AlfredAM** [comment]
@LLluoling 
do you have any advice on this? thanks.

**Comment by 1607722534** [comment]
I think he will reply only to suggestions that are useful to him. For example, when I submit a bug submitted earlier and ask for help, he will directly ignore it 🤢

**Comment by LLluoling** [comment]
Sorry about the late reply, so I'v been modifying the code lately.
In the paper, I used Monte Carlo search for RL learning. It's too slow.
Thus, to make public of the source code, I've add another RL algorithm, a2c, lately I realized it would be unstable when using 'a2c' training, I'm finding out.
If you guys are rushing, Can you please try train_option='monte'. I'll fix the a2c training ASAP
Sorry about the delay

**Comment by 1607722534** [comment]
Thank you for your reply. I'm waiting for your good news.

**Comment by AlfredAM** [comment]
while using 'monte' option, I encountered another error:

Saved ../../runs/seq2seq/test2/checkpoint_train_step_3000.pth
step=3000, train loss: 0.260, train reward: 0.843
step=3200, train loss: 0.245, train reward: 0.812
step=3400, train loss: 0.210, train reward: 0.760
Traceback (most recent call last):
  File "pipeline (pretrain & train & test)-ac2.py", line 102, in <module>
    trainer.train(data_loader, train_option='monte') 
  File "/home/recom/pens/pensmodule/Generator/train.py", line 161, in train
    user_embeds, news_body_indexes, news_body, news_vert, wd_strs, wd_indexes, src)
  File "/home/recom/pens/pensmodule/Generator/train.py", line 412, in get_reward
    decoder_input = torch.multinomial(torch.exp(step_output), 1)  # sampling (bz,1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by LLluoling** [comment]
it's wired. I've never encounter this problem. I'll update the code in two days. 
Could you please wait for two days and use the new code then [now I'm testing]

**Comment by AlfredAM** [comment]
Thanks a lot.

**Comment by AlfredAM** [comment]
Is there any update on this issue? Thanks.

**Comment by LLluoling** [comment]
I'm uploading code and the pretrained model, please check out in a few hours, thanks

**Comment by AlfredAM** [comment]
Thanks for your update! There're two residual issues:

# 1
pretrain loss: 49.668: 100%|██████████| 889/889 [13:34<00:00,  1.09it/s]
step= 500, pretrain loss: 61.421
Traceback (most recent call last):
  File "pipeline (pretrain & train & test).py", line 74, in <module>
    trainer.save_checkpoint(tag='pretrain_epoch_' + str(epoch))
  File "/home/recom/pens/pensmodule/Generator/train.py", line 94, in save_checkpoint
    ('model', self.model.module),
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'HeadlineGen' object has no attribute 'module'



# 2
step=3000, train actor loss: -0.179, train critic loss: 0.309, train reward: 3.424
multiple gpu training

  0%|          | 0/1288 [00:00<?, ?it/s]/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/modules/rnn.py:680: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at  /pytorch/aten/src/ATen/native/cudnn/RNN.cpp:924.)
  self.dropout, self.training, self.bidirectional, self.batch_first)
/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/functional.py:1794: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")

  0%|          | 0/1288 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "pipeline (pretrain & train & test).py", line 128, in <module>
    beam_size=3, eos_id=2)
  File "/home/recom/pens/pensmodule/Generator/eval.py", line 44, in predict
    model(src, None, None, user_embeds, 0)
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/recom/pens/venv/lib64/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer

**Comment by AlfredAM** [comment]
Hi, anyone else had the same issues?
Issue #1: 
AttributeError: 'HeadlineGen' object has no attribute 'module'

Issue #2
TypeError: expected sequence object with len >= 0 or a single integer

**Comment by AlfredAM** [comment]
@LLluoling  
Thanks for your update. Would you please comment on the issues mentioned above?

**Comment by LLluoling** [comment]
It seems that they are all caused by multi-gpu running, I changed the Generator/train/save_checkpoint function. If it still gets errors, you can try with single gpu

**Comment by AlfredAM** [comment]
The issues were fixed. Good job. Thanks!
