### ISSUE TITLE
Generator train wrong

### ISSUE THREAD

**Issue by zzqziv** [LLluoling/PENS-Personalized-News-Headline-Generation#7]
when i run the Generator train code'trainer.train(data_loader,train_option='a2c')', i got TypeError: 'GPT2Tokenizer' object is not callable.
it's a call wrong ?

**Comment by LLluoling** [comment]
It's probably due to the version of GPT2, you might try to add .tokenize, refer to https://github.com/huggingface/transformers/issues/5580

**Comment by 1607722534** [comment]
When I use NAML as the user interest extraction module, the training personalization generation will report an error:
 Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)
Is it my parameter setting problem?

**Comment by LLluoling** [comment]
try with x = x.long() in training

**Comment by 1607722534** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-9121fdad517b> in <module>
----> 1 rewards = trainer.train(data_loader,train_option='a2c', tag='mod4')

/home/data/zhangkui_data/PENS-Personalized-News-Headline-Generation-main/pensmodule/Generator/train.py in train(self, train_iter, train_option, tag, max_train_step)
    225                                         self.model(src, tgt_input, tgt_output, user_embeds, 0)
    226 
--> 227                 all_rewards = self.get_reward(sequences, lengths, wd_strs, wd_indexes, wd_str_lists, wd_index_lists, news_body, news_vert, news_body_indexes, news_body_split, user_embeds)
    228                 r = np.mean(np.sum(all_rewards, 1))
    229                 rewards.append(r)

/home/data/zhangkui_data/PENS-Personalized-News-Headline-Generation-main/pensmodule/Generator/train.py in get_reward(self, sequences, lengths, wd_strs, wd_indexes, wd_str_lists, wd_index_lists, news_body, news_vert, news_body_indexes, news_body_split, user_embeds, sos_id, eos_id)
    357         inds = deepcopy(lengths) - 1
    358         inds = inds.reshape(-1, 1)
--> 359         end_reward = self.get_per_reward(sequences, lengths, news_body, news_vert, user_embeds) + \
    360                         self.get_flu_reward2(sequences, wd_strs)
    361         end_reward = end_reward.reshape(-1, 1)

/home/data/zhangkui_data/PENS-Personalized-News-Headline-Generation-main/pensmodule/Generator/train.py in get_per_reward(self, seqs, sample_lengths, news_body, news_vert, user_embeds, sos_id, eos_id)
    373 
    374         with torch.no_grad():
--> 375             news_embeds = self.usermodel.news_encoder([seqs_new, news_vert, news_body]) # (bz, 64)
    376         personalized_r = torch.bmm(news_embeds.unsqueeze(1), user_embeds.unsqueeze(-1))# (bz, 1)
    377         personalized_r = personalized_r.squeeze(-1).squeeze(-1).detach().cpu().numpy()

/home/data/zhangkui_data/PENS-Personalized-News-Headline-Generation-main/pensmodule/UserEncoder/model.py in news_encoder(self, news_feature)
     42         body_len = body.shape[-1]
     43         body = body.reshape(-1, body_len)
---> 44         body = self.drop_layer(self.embed(body))
     45         body = self.drop_layer(self.attn_body(body, body, body))
     46         body = self.body_attn_pool(body).reshape(-1, 1, 400)

/usr/local/anaconda3/envs/kui1/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/anaconda3/envs/kui1/lib/python3.6/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    112         return F.embedding(
    113             input, self.weight, self.padding_idx, self.max_norm,
--> 114             self.norm_type, self.scale_grad_by_freq, self.sparse)
    115 
    116     def extra_repr(self):

/usr/local/anaconda3/envs/kui1/lib/python3.6/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1722         # remove once script supports set_grad_enabled
   1723         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1724     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1725 
   1726 

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)
