### ISSUE TITLE
about news recommendation model

### ISSUE THREAD

**Issue by 1607722534** [LLluoling/PENS-Personalized-News-Headline-Generation#8]
I see that the news recommendation model you implemented is different from the original model. For example, in the original NRMS model,The modeling user vector module uses multi head attention Did you use your changed model in your paper experiment?

**Comment by LLluoling** [comment]
No, I used two-layer multi-head attentions to compute user embedding in our paper. But I find the changed model that use attention pooling in the upper layer is faster in training.
However, either way aggregated in the final generation model shows similar performance.

**Comment by 1607722534** [comment]
Thank you for your reply.
