### ISSUE TITLE
The performance of the generator

### ISSUE THREAD

**Issue by 1607722534** [LLluoling/PENS-Personalized-News-Headline-Generation#9]
I tried different user interest models and embedded different methods, interest model results performed very well, but the results generated are ROUGE-1<25, ROUGE-2<9, ROUGE-L <22, the best performance of NAML in the paper, run out of ROUGE-1 around 24, what is the problem?

**Comment by LLluoling** [comment]
try with more pretraining  steps and some, increase batch size in training and grid search other parameters. I don't know if it's due to the a2c algorithm.
On the other hand, I remember that using entities in user encoder or generator would improve the performance a lot.

**Comment by 1607722534** [comment]
Thank you for your reply and I will try your suggestion.

**Comment by 1607722534** [comment]
Error "'Embedding' object has no attribute 'shape'" with TransformerEncoder, "Is there a problem with the input of "26 self.encoder" (args, self.embeddings)?

**Comment by 1607722534** [comment]
Is there a big difference in performance between  Transformer and LSTM in the model?

**Comment by Yuqi-Zhou** [comment]
> I tried different user interest models and embedded different methods, interest model results performed very well, but the results generated are ROUGE-1<25, ROUGE-2<9, ROUGE-L <22, the best performance of NAML in the paper, run out of ROUGE-1 around 24, what is the problem?


How did you solve this problem?
